name: Stella Quantum Radar Final

on:
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # 直接给它最高版本环境

      - name: Install
        run: pip install akshare ccxt pandas # 只装这三个最稳的

          
      - name: Run Radar
        run: python stella_radar.py
        
      - name: Deploy
        run: |
          git config --global user.name "Stella-Bot"
          git config --global user.email "stella-bot@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update Radar: $(date)" || exit 0
          git push origin main
